name: Build WASM

on:
  push:
    paths:
      - "inc/**.h"
      - "inc/**.hpp"
      - "src/**.c"
      - "src/**.cpp"
      - "www/wasm/**.h"
      - "www/wasm/**.c"
      - "www/wasm/Makefile"
      - "Makefile"
      - ".github/workflows/build-wasm.yml"
  pull_request:
    branches: [master]
    paths:
      - "inc/**.h"
      - "inc/**.hpp"
      - "src/**.c"
      - "src/**.cpp"
      - "www/wasm/**.h"
      - "www/wasm/**.c"
      - "www/wasm/Makefile"
      - "Makefile"
      - ".github/workflows/build-wasm.yml"
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"

jobs:
  build-wasm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # WASM
      - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@v12
      - name: WASM build
        working-directory: "./www/wasm"
        run: |
          emmake make
      # 打包
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: wasm-artifact
          path: www/wasm/target/*
