name: Doxygen

on:
  push:
    branches: [master]
    paths:
      - "src/**.c"
      - "inc/**.h"
      - "inc/**.hpp"
      - "support/Doxygen"
      - ".github/workflows/doxygen.yml"
  pull_request:
    branches: [master]
    paths:
      - "src/**.c"
      - "inc/**.h"
      - "inc/**.hpp"
      - "support/Doxygen"
      - ".github/workflows/doxygen.yml"
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"

# 保证权限合适
permissions:
  contents: read
  pages: write
  id-token: write

# 避免跳过部署
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build github pages
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Doxygen 样式
      - name: Doxygen scss compile
        uses: gha-utilities/sass-build@v0.6.0
        with:
          source: "./support/themes/doxygen/css/style.scss"
          destination: "./support/themes/doxygen/html/style.css"
          includePaths: "./support/themes/doxygen/:./support/themes/common/"
          outputStyle: compressed
      # Doxygen
      - name: Doxygen
        uses: mattnotmitt/doxygen-action@v1.9.8
        with:
          working-directory: "./"
          doxyfile-path: "support/Doxyfile"
      # 打包
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  # 进行部署 (仅master branch)
  deploy:
    if: github.ref == 'refs/heads/master'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
