name: Page eslint

on:
  push:
    paths:
      - "www/**.ts"
      - "www/**.js"
      - "www/.eslintrc.yml"
      - "www/.stylelintrc.json"
      - ".github/workflows/eslint.yml"
  pull_request:
    branches: [master]
    paths:
      - "www/**.ts"
      - "www/**.js"
      - "www/.eslintrc.yml"
      - "www/.stylelintrc.json"
      - ".github/workflows/eslint.yml"
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Yarn
        working-directory: "./www"
        run: |
          yarn install
          yarn lint
