name: "Code style"

on:
  push:
    paths:
      - "src/**.c"
      - "inc/**.h"
      - "inc/**.hpp"
      - "tests/**.c"
      - "tests/**.h"
      - "examples/**.c"
      - "examples/**.h"
      - "examples/**.hpp"
      - "**.clang-format"
      - ".github/workflows/format-checker.yml"
  pull_request:
    branches: [master]
    paths:
      - "src/**.c"
      - "inc/**.h"
      - "inc/**.hpp"
      - "tests/**.c"
      - "tests/**.h"
      - "examples/**.c"
      - "examples/**.h"
      - "examples/**.hpp"
      - "**.clang-format"
      - ".github/workflows/format-checker.yml"
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check code style
        uses: jidicula/clang-format-action@v4.13.0
        with:
          clang-format-version: "16"
          check-path: "./"
          fallback-style: Microsoft
