name: Page build

on:
  push:
    paths:
      - "www/**.ts"
      - "www/**.js"
      - "www/**.md"
      - "www/**.svg"
      - "www/**.html"
      - "www/**.scss"
      - "www/**.svelte"
      - ".github/workflows/pagebuild.yml"
  pull_request:
    branches: [master]
    paths:
      - "www/**.ts"
      - "www/**.js"
      - "www/**.md"
      - "www/**.svg"
      - "www/**.html"
      - "www/**.scss"
      - "www/**.svelte"
      - ".github/workflows/pagebuild.yml"
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@v11
      - name: WASM build
        working-directory: "./www/wasm"
        run: |
          emmake make
      - name: Yarn
        working-directory: "./www"
        run: |
          yarn install
          yarn build
      # 保存存档
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: "www"
          path: www/.svelte-kit/output/*
