name: Python lint

on:
  push:
    paths:
      - "zipack/**.py"
      - ".github/workflows/pylint.yml"
  pull_request:
    branches: [master]
    paths:
      - "zipack/**.py"
      - ".github/workflows/pylint.yml"
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f zipack/requirements.txt ]; then pip install -r zipack/requirements.txt; fi
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 ./zipack --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 ./zipack --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
